#if !defined(AFX_PLAYEROCX_H__A27E7B34_2FA6_4592_816A_1101048955DD__INCLUDED_)
#define AFX_PLAYEROCX_H__A27E7B34_2FA6_4592_816A_1101048955DD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPlayerOCX wrapper class

class CPlayerOCX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPlayerOCX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x25cdefd7, 0xe75f, 0x44f0, { 0x8e, 0x91, 0xaa, 0x94, 0xfc, 0x5b, 0x9b, 0x61 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetColorBackGround();
	void SetColorBackGround(unsigned long);

// Operations
public:
	long Login(long lDeviceType, LPCTSTR strAddress, long lPort, LPCTSTR strUserName, LPCTSTR strPassword, long* lpResult, long lReserved);
	long Logout(long lDeviceType, long lLoginHandle, long lReserved);
	long Initialize(long lDeviceType, long lFormatType, long lPlayMode, long lLoginHandle, long lReserved);
	long SetLoginHandle(long lLonginHandle, long lReserved);
	long OpenStream(LPCTSTR strAddress, long lPort, long lConnectType, long lChannel, long lReserved);
	long OpenPeriod(long lChannel, long lStartTime, long lEndTime, long lReserved);
	long OpenRemoteFile(LPCTSTR strFileName, long lReserved);
	long OpenLocalFile(LPCTSTR strFilePath, long lReserved);
	long PlayControl(long lControlCode, long lInValue, long* lpOutValue, long lReserved);
	long VideoCutControl(long lControlCode, long lInValue, long* lpOutValue, long lReserved);
	long PTZControl(long lControlCode, long lInValue, long* lpOutValue, long lReserved);
	long SetReduceLevel(long lSpatialLevel, long lFrameLevel, long lReserved);
	long GetReduceLevel(long* lpSpatialLevel, long* lpFrameLevel, long lReserved);
	long AddTextOverlay(long lPosX, long lPosY, LPCTSTR strText, long lColor, long* lpFont, long lStartTime, long lDuration, long lReserved);
	long AddSysTimeOverlay(long lPosX, long lPosY, long lRGB, long* lpFont, long lStartTime, long lDuration, long lReserved);
	long AddBitmapOverlay(long lPosX, long lPosY, long hBitmap, long lMaskColor, long lStartTime, long lDuration, long lReserved);
	long RemoveOverlay(long lOverlayHandle, long lReserved);
	long RemoveAllOverlay(long lReserved);
	long StartRecord(LPCTSTR strFilePath, LPCTSTR strFileName, LPCTSTR strStorageSourt, long lReserved);
	long StopRecord(long lReserved);
	long DownloadByTime(long lChannel, long lStartTime, long lEndTime, LPCTSTR strFilePath, long lReserved);
	long GetDownloadPosition(long lSaveHandle, long* lPostion, long lReserved);
	long StopDownload(long lSaveHandle, long lReserved);
	long SetColor(long lBright, long lContrast, long lSaturation, long lHue, long lReserved);
	long GetColor(long* lpBright, long* lpContrast, long* lpSaturation, long* lpHue, long lReserved);
	long SetFullScreenMode(long bFull, long lReserved);
	long GrabPicture(LPCTSTR strFilePath, long lReserved);
	long SetDecCB(long lpDecFunc, long lpParam, long lReserved);
	long GetVersions(LPCTSTR strVersions, long* lpStringLength, long lReserved);
	long GetLastError(long lReserved);
	long QueryDataDelivered(long lTime, long* lVideoDelivered, long* lAudioDelivered, long lReserved);
	long InputData(long pbData, long lDataLength);
	long SetVodCallBack(long ptrVodCallBack, long uSessionId, long lReserved);
	long VodCBResponsed(long lRetValue, long lReserved);
	long AddRectangleOverlay(long* lpTopLeftPoint, long* lpBottomRightPoint, long lColor, long lStartTime, long lDuration, long lReserved);
	long AddCircleOverlay(long* lpCenterPoint, long lRadii, long lColor, long lStartTime, long lDuration, long lReserved);
	long AddEllipseOverlay(long* lpTopLeftPoint, long* lpBottomRightPoint, long lColor, long lStartTime, long lDuration, long lReserved);
	long AddPolygonOverlay(long* lpPoints, long nCount, long lColor, long lStartTime, long lDuration, long lReserved);
	long SetFlickerTime(long lIndexNo, long lFlickerTime, long lReserved);
	long GetItemsByIndex(long lIndexNo, long* pbData, long* lpDataSize, long* lpCount, long lReserved);
	long AddOverlaysFromFile(LPCTSTR lpStrFilePath, long* lpOverlayCount, long lReserved);
	long AddOverlaysFromByte(long* pbData, long lDataLength, long* lpOveralyCount, long lReserved);
	long SetYUVFrameCallBack(long ptrYUVFrameCallBack, long uSessionId, long lReserved);
	long LoginCS(long lDeviceType, LPCTSTR strAddress, long lPort, LPCTSTR strUserName, LPCTSTR strPassword, long lpResult, long lReserved);
	long PlayControlCS(long lControlCode, long lInValue, long lpOutValue, long lReserved);
	long VideoCutControlCS(long lControlCode, long lInValue, long lpOutValue, long lReserved);
	long PTZControlCS(long lControlCode, long lInValue, long lpOutValue, long lReserved);
	long GetReduceLevelCS(long lpSpatialLevel, long lpFrameLevel, long lReserved);
	long AddTextOverlayCS(long lPosX, long lPosY, LPCTSTR strText, long lColor, long lpFont, long lStartTime, long lDuration, long lReserved);
	long AddSysTimeOverlayCS(long lPosX, long lPosY, long lRGB, long lpFont, long lStartTime, long lDuration, long lReserved);
	long GetDownloadPositionCS(long lSaveHandle, long lpPostion, long lReserved);
	long GetColorCS(long lpBright, long lpContrast, long lpSaturation, long lpHue, long lReserved);
	long GetVersionsCS(LPCTSTR strVersions, long lpStringLength, long lReserved);
	long QueryDataDeliveredCS(long lTime, long lVideoDelivered, long lAudioDelivered, long lReserved);
	long AddRectangleOverlayCS(long lpTopLeftPoint, long lpBottomRightPoint, long lColor, long lStartTime, long lDuration, long lReserved);
	long AddCircleOverlayCS(long lpCenterPoint, long lRadii, long lColor, long lStartTime, long lDuration, long lReserved);
	long AddEllipseOverlayCS(long lpTopLeftPoint, long lpBottomRightPoint, long lColor, long lStartTime, long lDuration, long lReserved);
	long AddPolygonOverlayCS(long lpPoints, long nCount, long lColor, long lStartTime, long lDuration, long lReserved);
	long GetItemsByIndexCS(long lIndexNo, long pbData, long lpDataSize, long lpCount, long lReserved);
	long AddOverlaysFromFileCS(LPCTSTR lpStrFilePath, long lpOverlayCount, long lReserved);
	long AddOverlaysFromByteCS(long pbData, long lDataLength, long lpOveralyCount, long lReserved);
	long SetNoVideoDisplay(BOOL bBKTextShow, LPCTSTR strBKText, long lBKTextColor, long lBKTextSize);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PLAYEROCX_H__A27E7B34_2FA6_4592_816A_1101048955DD__INCLUDED_)
