/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mingding.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2013
 * 
 * XDoclet definition:
 * @struts.form name="editConfigForm"
 */
public class EditConfigForm extends ActionForm
{
}
